[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "ğŸ”Œ "
discharging_symbol = "ğŸ’€ "
[[battery.display]]
threshold = 10
style = "bold red"
[[battery.display]]
threshold = 25
style = "bold yellow"

[character]
success_symbol = "[ğŸ¦†](bold green)"
error_symbol = "[ğŸ](bold red)"

[directory]
home_symbol="ğŸ¦š"
style="bold bright-yellow"

[git_status]
stashed=""
renamed=""
staged="ğŸŒ¯"
conflicted="ğŸ¤º"
ahead="ğŸš€"
behind="ğŸ›¶"
modified="ğŸŒ®"
diverged="ğŸ¤¦"
deleted="ğŸ”ª"
untracked="ğŸ™"
format="[$all_status$ahead_behind]($style) "

[git_branch]
format="[$branch]($style) "
style="bold bright-purple"

[docker_context]
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'compose.yaml', 'compose.yml', 'Containerfile', 'Dockerfile']

[direnv]
format="[$symbol$loaded/$allowed]($style) "
