[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "ğŸ”Œ "
discharging_symbol = "ğŸ’€ "
[[battery.display]]
threshold = 10
style = "bold red"
[[battery.display]]
threshold = 25
style = "bold yellow"

[character]
success_symbol = "[ğŸ¦†](bold green)"
error_symbol = "[ğŸ](bold red)"

[directory]
home_symbol="ğŸ¦š"
style="bold bright-yellow"

[git_status]
stashed=""
renamed=""
staged="ğŸŒ¯"
conflicted="ğŸ¤º"
ahead="ğŸš€"
behind="ğŸ›¶"
modified="ğŸŒ®"
diverged="ğŸ¤¦"
deleted="ğŸ”ª"
untracked="ğŸ™"
format="[$all_status$ahead_behind]($style) "

[git_branch]
format="[$branch]($style) "
style="bold bright-purple"

[docker_context]
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'compose.yaml', 'compose.yml', 'Containerfile', 'Dockerfile']


[package]
disabled=true
[dart]
disabled=true
[dotnet]
disabled=true
[elixir]
disabled=true
[elm]
disabled=true
[erlang]
disabled=true
[golang]
disabled=true
[java]
disabled=true
[julia]
disabled=true
[kotlin]
disabled=true
[ocaml]
disabled=true
[perl]
disabled=true
[php]
disabled=true
[purescript]
disabled=true
[python]
disabled=true
[ruby]
disabled=true
[rust]
disabled=true
[scala]
disabled=true
[swift]
disabled=true
[conda]
disabled=true
[aws]
disabled=true
[gcloud]
disabled=true
[openstack]
disabled=true
[crystal]
disabled=true
[lua]
disabled=true

